seed: 3
client_num: 50
client_sample_rate: 1
total_round: 200
algorithm: "FedPE"
client_sample_method: "random"
model_type: "LeNet"
dataset: "MNIST"
data_distribution: "non_iid"

gpu: 0
train_samples_per_client: 200
train_data_rate: 0.8
test_samples_per_client: 50
classes_per_client: 2
local_epoch: 10
learning_rate: 0.01
batch_size: 5
pruning_param: 18.0
expanding_param: 0.1
accuracy_threshold: 0.5
max_prune_rate: 0.9